name: Update Homebrew Formula
on:
  workflow_dispatch:
    inputs:
      version:
        description: Komac version
        required: true
        type: string
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download files, calculate hashes, and update formula
        run: |
          # Update the version in the formula
          (Get-Content -Raw ./komac.rb.template).Replace('<VERSION>','${{ github.event.inputs.version }}') | Out-File -NoNewline ./komac.rb

          # Update sha256 hashes
          (Get-Content -Raw ./komac.rb | Select-String -Pattern '(?<=sha256\s").*(?=")' -AllMatches).Matches.Value | ForEach-Object {
            (Get-Content -Raw ./komac.rb).Replace($_, $(curl -sL $_ | awk '{print $1}')) | Out-File -NoNewline ./komac.rb
          }

          # Commit and push changes
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add komac.rb
          git commit -m "Update komac to $version"
          git push
        shell: pwsh
