name: Update Homebrew Formula
on:
  workflow_dispatch:
    inputs:
      version:
        description: Komac version
        required: true
        type: string
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download files, calculate hashes, and update formula
        run: |
          VERSION="${{ github.event.inputs.version }}"
          
          # Create URLs for the release files
          BASE_URL="https://github.com/russellbanks/Komac/releases/download/v${VERSION}"
          MACOS_INTEL_URL="${BASE_URL}/komac-${VERSION}-x86_64-apple-darwin.tar.gz"
          MACOS_ARM_URL="${BASE_URL}/komac-${VERSION}-aarch64-apple-darwin.tar.gz"
          LINUX_INTEL_URL="${BASE_URL}/komac-${VERSION}-x86_64-unknown-linux-gnu.tar.gz"
          LINUX_ARM_URL="${BASE_URL}/komac-${VERSION}-aarch64-unknown-linux-gnu.tar.gz"
          
          # Download files and calculate SHA256 hashes
          echo "Downloading and calculating hashes..."
          MACOS_INTEL_SHA256=$(curl -sL "$MACOS_INTEL_URL" | shasum -a 256 | cut -d' ' -f1)
          MACOS_ARM_SHA256=$(curl -sL "$MACOS_ARM_URL" | shasum -a 256 | cut -d' ' -f1)
          LINUX_INTEL_SHA256=$(curl -sL "$LINUX_INTEL_URL" | shasum -a 256 | cut -d' ' -f1)
          LINUX_ARM_SHA256=$(curl -sL "$LINUX_ARM_URL" | shasum -a 256 | cut -d' ' -f1)
          
          echo "SHA256 hashes calculated:"
          echo "macOS Intel: $MACOS_INTEL_SHA256"
          echo "macOS ARM: $MACOS_ARM_SHA256"
          echo "Linux Intel: $LINUX_INTEL_SHA256"
          echo "Linux ARM: $LINUX_ARM_SHA256"
          
          # Update the formula from template
          cp ./komac.rb.template ./komac.rb
          
          # Replace placeholders with actual values
          sed -i '' "s/<VERSION>/${VERSION}/g" ./komac.rb
          sed -i '' "s/<SHA256_MACOS_INTEL>/${MACOS_INTEL_SHA256}/g" ./komac.rb
          sed -i '' "s/<SHA256_MACOS_ARM>/${MACOS_ARM_SHA256}/g" ./komac.rb
          sed -i '' "s/<SHA256_LINUX_INTEL>/${LINUX_INTEL_SHA256}/g" ./komac.rb
          sed -i '' "s/<SHA256_LINUX_ARM>/${LINUX_ARM_SHA256}/g" ./komac.rb
          
          # Commit and push changes
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add komac.rb
          git commit -m "Update komac to v${VERSION}"
          git push
        shell: bash
